# Generated by Django 5.2.9 on 2026-01-07 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("continuing_education", "0002_alter_continuingeducationmodel_id_course"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="continuingeducationmodel",
            table="continuing_education",
        ),
    ]
