# Generated by Django 5.2.9 on 2026-01-07 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="coursemodel",
            table="courses",
        ),
    ]
